services:    
  postgresql:
    container_name: postgresql-servidor
    image: postgres:15.4-bullseye
    networks:
      - mired
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=marce
      - POSTGRES_DB=cifradorUTNSB
      - POSTGRES_USER=marce
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./_data:/var/lib/postgresql/data
    restart: always

  pg-admin:
    container_name: pgadmin4_containerSB
    image: dpage/pgadmin4:8
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: marcelosola2001@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - mired

networks:
  mired:
