services:    
    postgresql:
        container_name: postgresql-servidor
        image: postgres:15.4-bullseye

        networks:
            - mired
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=${PASSWORD}
            - POSTGRES_DB=${DB}
            - POSTGRES_USER=${USER}
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            # es buena practica path relativo desde el proyecto ./_data:/var/lib/postgresql
            - ./_data:/var/lib/postgresql/data
        restart: always

networks:
    mired:
